//
//  File.swift
//  
//
//  Created by Joao Pedro Monteiro Maia on 08/03/24.
//

import Foundation

/// ClassName_Method_MockResponse

var ModelProvider_get_MockResponse = "{\"id\":\"640b517694bf816d35a59125\",\"name\":\"Chat GPT 3.5\",\"serviceName\":\"OpenAI InstructGPT\",\"status\":\"onboarded\",\"supplier\":{\"id\":1777,\"name\":\"OpenAI\",\"code\":\"openai\"},\"function\":{\"id\":\"text-generation\",\"name\":\"Text Generation\"},\"pricing\":{\"price\":0.000002,\"unitType\":\"TOKEN\",\"unitTypeScale\":null},\"version\":{\"name\":\"3.5\",\"id\":\"gpt-3.5-turbo\"},\"functionType\":\"ai\",\"type\":\"regular\",\"params\":[{\"name\":\"text\",\"required\":true,\"isFixed\":false,\"values\":[],\"defaultValues\":[],\"availableOptions\":[],\"dataType\":\"text\",\"dataSubType\":\"json\",\"multipleValues\":true},{\"name\":\"template\",\"required\":false,\"isFixed\":true,\"values\":[{\"value\":\"[{\\\"role\\\": \\\"user\\\", \\\"content\\\": \\\"<data>\\\"}]\",\"label\":\"Template\"}],\"defaultValues\":[],\"availableOptions\":[],\"dataType\":\"text\",\"dataSubType\":\"text\",\"multipleValues\":false},{\"name\":\"prompt\",\"required\":false,\"isFixed\":false,\"values\":[{\"value\":\" \",\"label\":\"Prompt\"}],\"defaultValues\":[],\"availableOptions\":[],\"dataType\":\"text\",\"dataSubType\":\"text\",\"multipleValues\":false},{\"name\":\"context\",\"required\":false,\"isFixed\":false,\"values\":[{\"value\":\" \",\"label\":\"Context\"}],\"defaultValues\":[],\"availableOptions\":[],\"dataType\":\"text\",\"dataSubType\":\"text\",\"multipleValues\":false},{\"name\":\"language\",\"required\":true,\"isFixed\":true,\"values\":[{\"value\":\"en\",\"label\":\"English\"}],\"defaultValues\":[],\"availableOptions\":[],\"dataType\":\"label\",\"dataSubType\":\"label\",\"multipleValues\":false},{\"name\":\"script\",\"required\":false,\"isFixed\":true,\"values\":[],\"defaultValues\":[],\"availableOptions\":[],\"dataType\":\"label\",\"dataSubType\":\"label\",\"multipleValues\":false},{\"name\":\"temperature\",\"required\":false,\"isFixed\":false,\"values\":[],\"defaultValues\":[{\"value\":\"0\",\"label\":\"0\"}],\"availableOptions\":[],\"dataType\":\"text\",\"dataSubType\":\"number\",\"multipleValues\":false},{\"name\":\"max_tokens\",\"required\":false,\"isFixed\":false,\"values\":[],\"defaultValues\":[{\"value\":\"200\",\"label\":\"200\"}],\"availableOptions\":[],\"dataType\":\"text\",\"dataSubType\":\"number\",\"multipleValues\":false},{\"name\":\"history\",\"required\":false,\"isFixed\":false,\"values\":[{\"value\":\" \",\"label\":\"default\"}],\"defaultValues\":[{\"value\":\"\",\"label\":\"default\"}],\"availableOptions\":[],\"dataType\":\"text\",\"dataSubType\":\"text\",\"multipleValues\":false}]}".data(using: .utf8)

var model_CreateExecution_MockResponse = "{\"completed\":false,\"data\":\"https://models.aixplain.com/api/v1/data/8d548248-c4b8-4051-b036-ccb0417f9cf1\",\"requestId\":\"8d548248-c4b8-4051-b036-ccb0417f9cf1\"}".data(using: .utf8)

var model_Polling_MockResponse = "{\"completed\":true,\"data\":\"Olá! Como posso ajudar você hoje?\",\"usedCredits\":0.000037999999999999995,\"runTime\":0.645,\"rawData\":{\"id\":\"chatcmpl-91wbcwddVCEPqgvY2iWGivhMppW2u\",\"object\":\"chat.completion\",\"created\":1710250636,\"model\":\"gpt-3.5-turbo-0125\",\"choices\":[{\"index\":0,\"message\":{\"role\":\"assistant\",\"content\":\"Olá! Como posso ajudar você hoje?\"},\"logprobs\":null,\"finish_reason\":\"stop\"}],\"usage\":{\"prompt_tokens\":8,\"completion_tokens\":11,\"total_tokens\":19},\"system_fingerprint\":\"fp_4f0b692a78\"}}".data(using: .utf8)
